theme: jekyll-theme-cayman
title: Ethan Han
description: I'm a Computer Science major at Vanderbilt interested in understanding the intersection of technology through design, business, and programming.
